StudentskaSluzba/StudentskaSluzba/Controllers/PredmetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudentskaSluzba.Data;
using StudentskaSluzba.Helper;
using StudentskaSluzba.Models;

namespace StudentskaSluzba.Controllers
{
    [Autorizacija(referent:true, student:false)]
    public class PredmetController : Controller
    {
        private readonly ApplicationDbContext _db;
        public PredmetController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(string pretraga)
        {
            List<Predmet> predmeti;
            if (!string.IsNullOrEmpty(pretraga))
            {
                predmeti = _db.Predmet.Where(p => p.Naziv.ToLower().StartsWith(pretraga.ToLower())).ToList();
            }
            else
            {
                predmeti = _db.Predmet.ToList();
            }
            ViewData["predmeti"] = predmeti;
            ViewData["pretraga"] = pretraga;

            return View();
        }

        public IActionResult AddEditPredmet(int id)
        {
            var predmet = id == 0 ? new Predmet() : _db.Predmet.Find(id);

            return View(predmet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEditPredmet(Predmet predmet)
        {
            Predmet p;
            if (predmet.Id == 0)
            {
                p = new Predmet();
                _db.Predmet.Add(p);
                TempData["poruka_p"] = "Uspjesno dodan predmet: ";
            }
            else
            {
                p = _db.Predmet.Find(predmet.Id);
                TempData["poruka_p"] = "Uspjesno uređen predmet: ";
            }

            p.ETCS = predmet.ETCS;
            p.Naziv = predmet.Naziv;

            if (!ModelState.IsValid)
            {
                return View(p);
            }

            _db.SaveChanges();
            TempData["poruka_p"] += p.Naziv;

            return View("Poruka");
        }

        public IActionResult Delete(int? id)
        {
            if (id != null || id != 0)
            {
                var obj = _db.Predmet.Find(id);
                _db.Remove(obj);
                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

StudentskaSluzba/StudentskaSluzba/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using StudentskaSluzba.Data;
using StudentskaSluzba.Helper;
using StudentskaSluzba.Models;
using StudentskaSluzba.ViewModels;

namespace StudentskaSluzba.Controllers
{
    [Autorizacija(referent: true, student: false)]
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public StudentController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string pretraga)
        {
            KorisnickiNalog korisnik = HttpContext.GetLogiraniKorisnik();

            if (korisnik == null)
            {
                TempData["error_poruka"] = "Nemate pravo pristupa";
                return RedirectToAction("Login", "Autentifikacija");
            }

            List<StudentiPrikazVM.Row> list =
                _db.Student.Where(s => pretraga == null || (s.Ime.ToLower() + " " + s.Prezime.ToLower()).StartsWith(pretraga.ToLower()))
                .Select(x => new StudentiPrikazVM.Row
                {
                    Id = x.Id,
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    GodinaStudija = x.GodinaStudija.Godina,
                    Grad = x.Grad.Naziv,
                    AdresaStanovanja = x.AdresaStanovanja,
                    DatumRodjenja = x.DatumRodjenja,
                    JMBG = x.JMBG,
                    Email = x.Email,
                }).ToList();

            StudentiPrikazVM sp = new StudentiPrikazVM();
            sp.Studenti = list;
            sp.pretraga = pretraga;

            return View(sp);
        }

        public IActionResult Add()
        {
            IEnumerable<Grad> gradovi = _db.Grad.ToList();
            IEnumerable<GodinaStudija> godine = _db.GodinaStudja.ToList();

            ViewData["gradkey"] = gradovi;
            ViewData["godinekey"] = godine;
            Student student = new Student();
            ViewData["student"] = student;

            return View("Edit");
        }

        public IActionResult Poruka(int? id)
        {
            var student = _db.Student.Find(id);

            ViewData["student"] = student;
            return View();
        }

        // DELETE Student
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                var obj = _db.Student.Find(id);
                _db.Remove(obj);
                _db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // ADD OR UPDATE
        public IActionResult AddEdit(int id)
        {
            List<SelectListItem> opstine = _db.Grad.Select(g => new SelectListItem
            {
                Text = g.Naziv,
                Value = g.Id.ToString()
            }).ToList();

            List<SelectListItem> godine = _db.GodinaStudja.Select(god => new SelectListItem
            {
                Text = god.Godina.ToString(),
                Value = god.Id.ToString()
            }).ToList();

            StudentVM student = id == 0 ? new StudentVM
            {
                Opcine = opstine,
                GodineStudija = godine
            } :
            _db.Student
                .Select(x => new StudentVM
                {
                    Id = x.Id,
                    Ime = x.Ime,
                    Prezime = x.Prezime,
                    AdresaStanovanja = x.AdresaStanovanja,
                    DatumRodjenja = x.DatumRodjenja,
                    JMBG = x.JMBG,
                    Email = x.Email,
                    GodinaStudijaId = x.GodinaStudijaId,
                    GradId = x.GradId,
                    Opcine = opstine,
                    GodineStudija = godine
                })
                .Where(x => x.Id == id).Single();

            return View("AddEdit", student);
        }

        // ADD OR UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddEdit(StudentVM s)
        {
            if (!ModelState.IsValid)
            {
                List<SelectListItem> opstine = _db.Grad.Select(g => new SelectListItem
                {
                    Text = g.Naziv,
                    Value = g.Id.ToString()
                }).ToList();

                List<SelectListItem> godine = _db.GodinaStudja.Select(god => new SelectListItem
                {
                    Text = god.Godina.ToString(),
                    Value = god.Id.ToString()
                }).ToList();

                s.Opcine = opstine;
                s.GodineStudija = godine;

                return View("AddEdit", s);
            }

            Student student;
            if (s.Id == 0)
            {
                student = new Student();
                _db.Add(student);
                TempData["poruka"] = "Uspjesno ste dodali studenta: ";
            }
            else
            {
                student = _db.Student.Find(s.Id);
                TempData["poruka"] = "Uspjesno ste editovali studenta: ";
            }

            student.Ime = s.Ime;
            student.Prezime = s.Prezime;
            student.AdresaStanovanja = s.AdresaStanovanja;
            student.GodinaStudijaId = s.GodinaStudijaId;
            student.GradId = s.GradId;
            student.JMBG = s.JMBG;
            student.DatumRodjenja = s.DatumRodjenja;
            student.Email = s.Email;

            _db.SaveChanges();

            TempData["poruka"] += student.ToString();
            return RedirectToAction("Poruka");
        }

        public IActionResult Uspjeh(int? id)
        {
            var student = _db.Student
                        .Include(s => s.Uspjeh)
                        .ThenInclude(s => s.Predmet)
                        .SingleOrDefault(s => s.Id == id);

            return View(student);
        }

        public IActionResult DeleteUspjeh(int? id)
        {
            if (id != null || id != 0)
            {
                var obj = _db.Uspjeh.Find(id);
                _db.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Uspjeh", new { id = obj.StudentId });
            }
            return RedirectToAction("Index");
        }

        public IActionResult AddUspjeh(int id)
        {
            if (id != 0)
            {
                List<SelectListItem> predmeti = _db.Predmet
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Naziv
                    }).ToList();
                StudentUspjehVM uspjeh = new StudentUspjehVM
                {
                    DatumPolaganja = DateTime.Now,
                    StudentId = id,
                    Predmeti = predmeti
                };
                return View("EditUspjeh", uspjeh);
            }

            return View("Index");
        }

        public IActionResult EditUspjeh(int id)
        {
            List<SelectListItem> predmeti = _db.Predmet
                .Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Naziv
                }).ToList();

            StudentUspjehVM u = _db.Uspjeh
                .Select(x => new StudentUspjehVM
                {
                    Id = x.Id,
                    PredmetId = x.PredmetId,
                    StudentId = x.StudentId,
                    DatumPolaganja = x.DatumPolaganja,
                    Ocjena = x.Ocjena,
                    Predmeti = predmeti
                })
                .Where(x => x.Id == id)
                .Single();

            return View(u);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditUspjeh(StudentUspjehVM sp)
        {
            if (!ModelState.IsValid)
            {
                List<SelectListItem> predmeti = _db.Predmet
                    .Select(x => new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Naziv
                    }).ToList();

                sp.Predmeti = predmeti;

                return View(sp);
            }

            StudentiPredmeti uspjeh;
            if (sp.Id == 0)
            {
                uspjeh = new StudentiPredmeti();
                _db.Add(uspjeh);
            }
            else
            {
                uspjeh = _db.Uspjeh.Find(sp.Id);
            }

            uspjeh.Ocjena = sp.Ocjena;
            uspjeh.PredmetId = sp.PredmetId;
            uspjeh.StudentId = sp.StudentId;
            uspjeh.DatumPolaganja = sp.DatumPolaganja;

            _db.SaveChanges();
            return RedirectToAction("Uspjeh", new { id = uspjeh.StudentId });
        }
    }
}

StudentskaSluzba/StudentskaSluzba/Views/Shared/_Layout.cshtml
@using StudentskaSluzba.Helper
@using Microsoft.AspNetCore.Http
@using StudentskaSluzba.Models

@{
    KorisnickiNalog nalog = Context.GetLogiraniKorisnik();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentskaSluzba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha512-2JBCbWoMJPH+Uj7Wq5OLub8E5edWHlTM4ar/YJkZh3plwB2INhhOC3eDoqHm1Za/ZOSksrLlURLoyXVdfQXqwg==" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha512-PMjWzHVtwxdq7m7GIxBot5vdxUY+5aKP9wpKtvnNBZrVv1srI8tU6xvFMzG8crLNcMj/8Xl/WWmo/oAP/40p1g==" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index">StudentskaSluzba</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Studenti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predmet" asp-action="Index">Predmeti</a>
                        </li>
                        @{
                            if (nalog != null)
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Autentifikacija" asp-action="Logout">@nalog?.Email Logout</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StudentskaSluzba - <a asp-area="" asp-controller="Student" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>